// Classroom layout derived from user-supplied screenshots. It is not VLearn source code.
window.VL_UI=(()=>{
 let sidebar=true;
 const button=(text,action,extra='')=>`<button class="btn" data-action="${action}" ${extra}>${text}</button>`;
 function frame({option,stage,slide,lesson,support,extra='',dock=true,floating='',notice='',hasSuggestion=false}){
  const toolbar=`<nav class="viewer-toolbar" aria-label="Công cụ tài liệu"><span class="viewer-label">▣ Từng trang</span><span class="viewer-label">Tài liệu mẫu</span><span class="viewer-page">${button('‹','prev',slide===5?'disabled aria-label="Slide trước"':'aria-label="Slide trước"')}<b>${slide} / 7</b>${button('›','next',slide===7?'disabled aria-label="Slide tiếp"':'aria-label="Slide tiếp"')}</span>${button('Sổ ghi chú','notes-open')}${button('Quiz ↓','quiz-view')}</nav>`;
  lesson=lesson.replace(/<nav class="nav"[\s\S]*?<\/nav>/,(floating?`<aside class="floating-radar" aria-label="Gợi ý cạnh tài liệu">${floating}</aside>`:'')+toolbar);
  return `<header class="classroom-header"><button class="icon-button" data-ui="sidebar" aria-label="${sidebar?'Thu gọn':'Mở'} nội dung bài học">☰</button><div class="lesson-title">Bài 02 · Hệ thống hỏi đáp — RAG</div><span class="prototype-label">Bản thử ${option.toUpperCase()}</span><span class="language-label">VI</span><div class="header-actions">${button(option==='a'?'Đặt câu hỏi':'✦ Đặt câu hỏi với AI'+(hasSuggestion?' <span class="suggestion-badge">Có gợi ý</span>':''),'tutor-open')}${button('♧ Gửi yêu cầu','manual-draft')}</div><button class="icon-button" data-action="reset" aria-label="Làm lại từ đầu" title="Làm lại từ đầu">↺</button><span class="avatar" aria-label="Học viên giả lập">P</span></header><div class="classroom ${!sidebar?'sidebar-hidden':''} ${dock?'dock-open':''}"><aside class="lesson-sidebar"><div class="sidebar-heading">NỘI DUNG BÀI HỌC <button class="icon-button" data-ui="sidebar" aria-label="Ẩn danh mục">×</button></div><div class="sidebar-body"><h3>HỆ THỐNG HỎI ĐÁP</h3><hr><strong>Slide bài giảng</strong><p class="quiet">Bộ tài liệu mẫu · dùng chung A/B/C</p>${[5,6,7].map(n=>`<button class="lesson-link ${slide===n?'current':''}" data-action="goto" data-slide="${n}"><span class="lesson-icon">▣</span><span>Slide ${n}: ${window.VL_FIXTURE.slides[n].title}</span>${slide===n?'<small>Đang học</small>':''}</button>`).join('')}<hr><strong>Tự kiểm tra</strong><button class="lesson-link" data-action="quiz-view"><span class="lesson-icon">✓</span><span>Quiz: Truy xuất và sinh câu trả lời</span></button><div class="sidebar-foot"><a href="../index.html">← Bộ A / B / C</a>${button('↺ Làm lại từ đầu','reset')}<p>Không lưu phiên · Không gửi ra ngoài</p></div></div></aside><main class="lesson-workspace"><div class="lab-context"><strong>Nhiệm vụ:</strong> ${window.VL_FIXTURE.task}</div><div class="steps">${['Bài học','Làm rõ & kiểm tra','Quyết định / kết quả'].map((v,i)=>`<span class="${i===stage?'active':''}" ${i===stage?'aria-current="step"':''}><b>${i+1}</b>${v}</span>`).join('')}</div>${extra}${!dock?`<div class="notice" role="status" aria-live="polite">${notice}</div>`:''}<div class="viewer-area">${lesson}</div><div class="activity-footer"><span>Nội dung, AI và coach mô phỏng</span>${button('Đi tới quiz →','quiz-view')}</div></main>${dock?`<aside class="assistant-dock" aria-label="Khung hỗ trợ">${support}</aside>`:''}</div>`;
 }
 document.addEventListener('click',e=>{const el=e.target.closest('[data-ui]');if(el?.dataset.ui==='sidebar'){sidebar=!sidebar;document.querySelector('.classroom')?.classList.toggle('sidebar-hidden',!sidebar);}const a=e.target.closest('[data-action]')?.dataset.action;if(a==='quiz-view'){const quiz=document.querySelector('.quiz');quiz?.scrollIntoView({behavior:'smooth',block:'center'});quiz?.querySelector('input')?.focus({preventScroll:true});}});
 return {frame,reset(){sidebar=true;}};
})();
