(() => {
  'use strict';
  const option = document.body.dataset.option;
  const app = document.getElementById('app');
  const slides = {
    5: {title:'Khi câu trả lời thiếu căn cứ', text:'Mô hình có thể tạo câu trả lời nghe hợp lý nhưng không đúng với tài liệu của lớp.', bullets:['Một câu trả lời trôi chảy chưa bảo đảm là đúng.','Cần tài liệu phù hợp với câu hỏi để kiểm tra căn cứ.']},
    6: {title:'RAG: tìm tài liệu rồi trả lời', text:'RAG (Retrieval-Augmented Generation) kết hợp truy xuất tài liệu với sinh câu trả lời.', bullets:['Truy xuất: tìm đoạn tài liệu liên quan đến câu hỏi.','Sinh câu trả lời: dùng câu hỏi và đoạn tài liệu đó để tạo phản hồi.']},
    7: {title:'Bốn bước của RAG', text:'Tài liệu tìm được trở thành ngữ cảnh cho mô hình.', bullets:['1. Nhận câu hỏi của người dùng.','2. Tìm đoạn tài liệu liên quan.','3. Đưa đoạn tài liệu cùng câu hỏi vào mô hình.','4. Mô hình sinh câu trả lời dựa trên ngữ cảnh.']}
  };
  const explanation = 'Truy xuất tìm các đoạn liên quan. Sinh câu trả lời dùng câu hỏi cùng các đoạn đó để tạo phản hồi. Ví dụ hỏi chính sách đổi trả: truy xuất tìm đoạn chính sách, rồi mô hình dùng đoạn đó để trả lời.';
  const coachReply = 'Bạn có thể hình dung truy xuất là tìm trang tài liệu cần đọc, còn sinh câu trả lời là dùng trang đó để trả lời câu hỏi. Hãy thử chỉ ra bước tìm tài liệu trong quiz.';
  const fresh = () => ({slide:6,stage:0,mode:'start',returnMode:'form',question:'',draft:'',kind:'Khái niệm / thuật ngữ',recipient:'Lab coach — hỗ trợ khái niệm',named:false,name:'',share:false,sourceSlide:6,query:'',answer:'',unsupported:false,quiz:'',checked:false,enabled:false,visits:0,started:0,suggestions:0,dismissed:false,prompt:false,reason:'',coach:false,submitted:false,message:'',why:false});
  let s = fresh();
  const esc = value => String(value).replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const btn = (label,action,kind='',extra='') => `<button class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
  const box = (text,kind='') => `<div class="box ${kind}">${text}</div>`;
  const renderQuiz = () => `<section class="quiz"><div class="eyebrow">Tự kiểm tra</div><h3 style="margin-top:6px">Một câu hỏi để tiếp tục</h3><fieldset><legend>Trong RAG, bước nào tìm tài liệu liên quan?</legend>${['Truy xuất','Sinh câu trả lời','Gửi thông báo','Chấm điểm'].map((v,i)=>`<label class="choice"><input type="radio" name="quiz" value="${i}" ${s.quiz===String(i)?'checked':''}>${v}</label>`).join('')}</fieldset>${btn('Kiểm tra câu trả lời','check','subtle')}${s.checked?box(s.quiz==='0'?'Đúng với slide 7: bước 2 là truy xuất. Một câu đúng chưa chứng minh bạn đã hiểu sâu.':'Đáp án chưa khớp slide 7. Bạn có thể đọc lại hoặc tiếp tục yêu cầu hỗ trợ.',''+(s.quiz==='0'?'success':'warn')):''}</section>`;
  function lesson() {
    const x=slides[s.slide];
    return `<section class="card"><div class="card-title"><h2>Nội dung học</h2><span class="tag">Slide ${s.slide} / 7</span></div><div class="card-body"><article class="slide"><div class="eyebrow">Bài 02 · Hệ thống hỏi đáp</div><h2 style="margin-top:10px">${x.title}</h2><p>${x.text}</p><ul>${x.bullets.map(t=>`<li>${t}</li>`).join('')}</ul>${s.slide===6?'<div class="flow"><span>01 · Câu hỏi</span><span>02 · Tìm tài liệu</span><span>03 · Trả lời</span></div>':''}</article><nav class="nav" aria-label="Chuyển slide">${btn('← Slide trước','prev','',s.slide===5?'disabled':'')}<div class="dots" aria-hidden="true">${[5,6,7].map(n=>`<span class="${n===s.slide?'on':''}"></span>`).join('')}</div>${btn('Slide tiếp →','next','',s.slide===7?'disabled':'')}</nav>${renderQuiz()}</div></section>`;
  }
  function controlsC(){
    return `<div class="toggle"><label for="enabled">Gợi ý trong phiên này</label><input id="enabled" type="checkbox" ${s.enabled?'checked':''}></div><p class="quiet">Khi bật, dùng thời gian ở slide và số lần quay lại. Chỉ dùng tín hiệu sau khi bạn bật; không đọc ghi chú, quiz hay chat. Tắt để xóa tín hiệu. Tín hiệu không chứng minh bạn chưa hiểu.</p>`;
  }
  function start(){
    if(option==='a') return `<div class="empty-icon" aria-hidden="true">↗</div><h2>Bạn muốn hỏi phần nào?</h2><p class="muted">Chọn chỗ vướng và viết câu hỏi. Hệ thống gắn slide hiện tại, không tự suy đoán bạn chưa hiểu gì.</p>${box('Chỉ gửi cho coach khi bạn đã xem trước và xác nhận. Phản hồi trong bản thử này là mô phỏng.','neutral')}${btn('Đánh dấu & tạo câu hỏi','form','primary wide')}<p class="quiet">Bạn có thể tiếp tục đọc slide hoặc làm quiz mà không gửi.</p>`;
    if(option==='b') return `<div class="empty-icon" aria-hidden="true">✦</div><h2>Làm rõ một khái niệm</h2><p class="muted">Bạn đặt câu hỏi; trợ lý giải thích trong phạm vi slide 5–7. Nếu chưa rõ, bạn có thể chuyển câu hỏi cho coach.</p>${box('Trợ lý có thể giải thích sai hoặc chưa đủ. Hãy kiểm tra nguồn trước khi dùng.','warn')}${btn('Hỏi trợ lý','chat','primary wide')}<p class="quiet">Bạn quyết định có dùng câu trả lời và có gửi coach hay không.</p>`;
    const prompt=s.prompt?`<div class="radar-prompt">${box(`<strong>Bạn có cần làm rõ phần này không?</strong><p class="small" style="margin-top:7px">Đây chỉ là suy đoán, có thể sai. Xem lại slide không đồng nghĩa bạn chưa hiểu.</p>`)}<button class="linkbutton" data-action="why">${s.why?'Ẩn căn cứ':'Vì sao mình hỏi?'}</button>${s.why?box(esc(s.reason),'neutral'):''}<div class="actions">${btn('Giải thích','explain','primary')}${btn('Nhờ coach','form')}${btn('Để sau','later')}${btn('Không cần giúp','reject')}${btn('Tắt gợi ý','disable')}</div></div>`:box(s.enabled?'Gợi ý đang bật. Bạn cứ tiếp tục học; mình chỉ hỏi khi có tín hiệu cần hỗ trợ. Tối đa 2 gợi ý trong phiên.':'Gợi ý đang tắt. Bạn vẫn có thể hỏi trợ lý hoặc tự viết câu hỏi.','neutral');
    return `<div class="empty-icon" aria-hidden="true">◌</div><h2>VLearn Tutor</h2>${controlsC()}${prompt}<div class="actions">${btn('Tự viết câu hỏi','form')}${btn('Hỏi trợ lý','chat')}</div><p class="quiet">Không tự gắn cờ hoặc báo coach. Bạn luôn quyết định nội dung gửi.</p>`;
  }
  function form(){return `<h2>Câu hỏi cho coach</h2><p class="muted small">Viết đúng chỗ bạn đang vướng. Câu hỏi chưa được gửi.</p><label for="sourceSlide">Vị trí cần hỗ trợ</label><select id="sourceSlide">${[5,6,7].map(n=>`<option value="${n}" ${s.sourceSlide===n?'selected':''}>Slide ${n} — ${slides[n].title}</option>`).join('')}</select><label for="kind">Loại chỗ vướng</label><select id="kind">${['Khái niệm / thuật ngữ','Cách các bước liên hệ','Câu hỏi khác'].map(v=>`<option ${s.kind===v?'selected':''}>${v}</option>`).join('')}</select><label for="question">Câu hỏi của bạn</label><textarea id="question" placeholder="Mình chưa rõ…">${esc(s.question)}</textarea>${box('Hệ thống chỉ giữ nội dung bạn viết, không thêm nguyên nhân hoặc kết luận về năng lực.','neutral')}<div class="actions">${btn('Xem trước','preview','primary')}${btn('Quay lại bài học','close')}</div>`;}
  function chat(){return `<h2>Hỏi về slide</h2><p class="muted small">Nguồn: slide 5–7. Phản hồi được soạn sẵn cho bản thử.</p><label for="query">Bạn muốn làm rõ điều gì?</label><textarea id="query" placeholder="Ví dụ: truy xuất khác sinh câu trả lời thế nào?">${esc(s.query)}</textarea><div class="actions">${btn('Truy xuất & sinh câu trả lời','ask-rag','subtle')}${btn('Cách chọn top-k','ask-topk')}${btn('Gửi câu hỏi','ask','primary')}${btn('Tự viết cho coach','form')}${btn('Quay lại bài học','close')}</div>`;}
  function answer(){return `<h2>Lời giải để bạn kiểm tra</h2>${box('Nội dung mô phỏng; trợ lý chỉ dùng slide 5–7.','neutral')}<p>${esc(s.answer)}</p><div class="badge-row"><span class="tag">${s.unsupported?'Chưa có căn cứ trong slide':'Có căn cứ trong slide'}</span></div><p class="small muted">Nhãn mô tả phạm vi tài liệu, không phải xác suất AI đúng.</p><details><summary>Nguồn và giới hạn</summary><div class="box neutral">${s.unsupported?'Slide 5–7 không nói cách chọn top-k hoặc trả lời câu hỏi này. Không tự đoán.':'Slide 6 định nghĩa RAG; slide 7, bước 2 tìm tài liệu và bước 4 sinh câu trả lời.'}</div></details><div class="actions">${btn('Mình đã rõ → quiz','understood','primary')}${btn('Vẫn chưa rõ → coach','draft')}${btn('Hỏi phần khác','chat')}${btn('Tự viết thay bản nháp','form')}</div>`;}
  function preview(){return `<h2>Kiểm tra trước khi gửi</h2><p class="muted small">Bản nháp có thể chưa diễn đạt đúng ý bạn. Hãy sửa trước khi gửi.</p><label for="draft">Nội dung yêu cầu</label><textarea id="draft">${esc(s.draft)}</textarea><label for="recipient">Người nhận</label><select id="recipient">${['Lab coach — hỗ trợ khái niệm','TA — hỗ trợ bài tập'].map(v=>`<option ${s.recipient===v?'selected':''}>${v}</option>`).join('')}</select><label class="control"><input id="named" type="checkbox" ${s.named?'checked':''}>Kèm tên của tôi</label>${s.named?`<label for="name">Tên hiển thị (chỉ dùng tên giả lập)</label><input type="text" id="name" value="${esc(s.name)}" placeholder="Ví dụ: Học viên 01">`:''}${option==='c'&&s.reason?`<label class="control"><input id="share" type="checkbox" ${s.share?'checked':''}>Kèm tín hiệu phiên này</label><p class="quiet">${esc(s.reason)} — đây là tín hiệu, không phải kết luận chưa hiểu.</p>`:''}<div class="preview"><dl><dt>Coach sẽ thấy</dt><dd id="previewIdentity">${s.named?esc(s.name||'Chưa nhập tên'):'Không kèm tên'}</dd><dt>Vị trí</dt><dd>Slide ${s.sourceSlide} · ${esc(s.kind)}</dd><dt>Người nhận</dt><dd id="previewRecipient">${esc(s.recipient)}</dd><dt>Nội dung</dt><dd id="previewDraft">${esc(s.draft)}</dd><dt>Tín hiệu</dt><dd id="previewSignal">${s.share&&s.reason?esc(s.reason):'Không chia sẻ'}</dd></dl></div><div class="actions">${btn('Xác nhận gửi','send','primary')}${btn('Sửa vị trí / viết lại','edit')}${btn('Không gửi','cancel')}</div>`;}
  function result(){if(s.mode==='learning')return `<h2>Bạn chọn tiếp tục học</h2>${box('Bạn có thể trả lời quiz và đối chiếu với slide. Không gửi câu hỏi hoặc dữ liệu cho coach.','success')}<p class="muted">Một lựa chọn “đã rõ” chưa chứng minh bạn hiểu sâu. Nếu cần, bạn vẫn có thể hỏi thêm.</p><div class="actions">${btn('Quay lại bài học','close','primary')}${btn('Hỏi phần khác','chat')}${btn('Tự viết cho coach','form')}</div>`;return `<h2>${s.submitted?'Yêu cầu đã gửi':'Đã thu hồi yêu cầu'}</h2>${box(s.submitted?'Mô phỏng — không gửi dữ liệu hoặc liên hệ coach thật.':'Yêu cầu được thu hồi trước khi đọc phản hồi mô phỏng.',s.submitted?'success':'neutral')}<p class="small muted">${esc(s.recipient)} · Slide ${s.sourceSlide} · ${s.named?esc(s.name):'Không kèm tên'}</p><div class="box neutral">${esc(s.draft).replace(/\n/g,'<br>')}</div>${s.submitted&&!s.coach?`<p class="quiet">Phản hồi coach là nội dung soạn sẵn để thử luồng, không phải cam kết thời gian chờ.</p><div class="actions">${btn('Đọc phản hồi mô phỏng','coach','primary')}${btn('Sửa yêu cầu','edit-sent')}${btn('Thu hồi','withdraw','danger')}</div>`:''}${s.coach?`${box('<strong>Coach — phản hồi mô phỏng</strong><p style="margin-top:8px">'+coachReply+'</p>')}<p class="quiet">Phản hồi đã được mở. Không hứa xóa nội dung người nhận đã đọc; bạn có thể gửi câu hỏi tiếp.</p><div class="actions">${btn('Hỏi thêm','followup')}${btn('Quay lại quiz','close','primary')}</div>`:`<div class="actions">${btn('Quay lại bài học','close')}${!s.submitted?btn('Viết lại câu hỏi','form'):''}</div>`}`;}
  function support(){let content=s.stage===2?result():s.stage===0?start():({form,chat,answer,preview}[s.mode]||start)();return `<section class="card"><div class="card-title"><h2>Hỗ trợ học tập</h2>${option==='c'&&s.stage!==0?btn(s.enabled?'Tắt gợi ý':'Gợi ý đang tắt','disable','',s.enabled?'':'disabled'):''}</div><div class="card-body">${content}<div class="notice" role="status" aria-live="polite">${esc(s.message)}</div></div></section>`;}
  function render(){const stage=s.stage;app.innerHTML=`<header><div class="brand"><span class="mark" aria-hidden="true">V</span>VLearn <span class="tag">Bản thử ${option.toUpperCase()}</span></div><div class="top-actions"><a href="../index.html">Bộ A / B / C</a>${btn('↺ Làm lại từ đầu','reset')}</div></header><div class="coursebar"><strong>AI Thực Chiến <span style="color:#a3a3a3;margin:0 10px">/</span> Bài 02 · Hệ thống hỏi đáp</strong><span>Không gian học mô phỏng · Slide 5–7</span></div><main class="shell"><div class="eyebrow">Tự học · Kiến thức AI</div><h1>Hiểu RAG, tiếp tục bài học</h1><p class="muted">Đọc slide, làm rõ chỗ vướng và tự quyết định cách nhận hỗ trợ.</p><div class="task"><span class="task-num">→</span><div><strong>Nhiệm vụ của bạn</strong><p>Bạn chưa rõ truy xuất khác sinh câu trả lời thế nào. Hãy làm rõ rồi trả lời quiz. Nếu vẫn chưa rõ, chuyển câu hỏi tới người hỗ trợ theo mức chia sẻ bạn chọn.</p></div></div><div class="steps">${['Bài học','Làm rõ & kiểm tra','Quyết định / kết quả'].map((v,i)=>`<span class="${i===stage?'active':''}" ${i===stage?'aria-current="step"':''}><b>${i+1}</b>${v}</span>`).join('')}</div><div class="grid">${lesson()}${support()}</div><div class="footer"><span>Bản thử tương tác · Nội dung và phản hồi AI/coach được soạn sẵn.</span><span>Không lưu phiên · Không gửi ra ngoài</span></div></main>`;}
  function field(id){return document.getElementById(id)?.value||'';}
  function saveForm(){s.question=field('question');s.kind=field('kind')||s.kind;s.sourceSlide=Number(field('sourceSlide')||s.sourceSlide);}
  function savePreview(){s.draft=field('draft');s.recipient=field('recipient')||s.recipient;s.name=field('name')||s.name;}
  function setMode(mode){s.stage=1;s.mode=mode;s.message='';render();}
  function updatePreview(){const map={previewIdentity:s.named?s.name||'Chưa nhập tên':'Không kèm tên',previewRecipient:s.recipient,previewDraft:s.draft,previewSignal:s.share&&s.reason?s.reason:'Không chia sẻ'};for(const [id,value]of Object.entries(map)){const el=document.getElementById(id);if(el)el.textContent=value;}}
  function answerQuery(query){s.query=query;const q=query.toLowerCase();s.unsupported=/top.?k|chọn k/.test(q)||!/rag|truy xuất|sinh|tài liệu|retrieval/.test(q);s.answer=s.unsupported?'Slide 5–7 chưa đủ căn cứ trả lời câu hỏi này. Bạn có thể làm rõ câu hỏi hoặc nhờ coach; trợ lý không tự đoán.':explanation;setMode('answer');}
  function disable(){s.enabled=false;s.visits=0;s.started=0;s.reason='';s.prompt=false;s.share=false;s.dismissed=false;s.message='Đã tắt và xóa tín hiệu phiên. Câu hỏi bạn viết vẫn được giữ.';render();}
  document.addEventListener('input',e=>{const id=e.target.id;if(['question','query','draft','name'].includes(id)){s[id]=e.target.value;updatePreview();}});
  document.addEventListener('change',e=>{const id=e.target.id;if(e.target.name==='quiz'){s.quiz=e.target.value;s.checked=false;return;}if(id==='enabled'){s.enabled=e.target.checked;s.visits=s.enabled&&s.slide===6?1:0;s.started=s.enabled?Date.now():0;s.dismissed=false;s.reason='';s.prompt=false;s.share=false;s.message=s.enabled?'Đã bật gợi ý cho phiên này.':'Đã tắt và xóa tín hiệu phiên.';render();}else if(id==='named'){savePreview();s.named=e.target.checked;render();}else if(id==='share'){s.share=e.target.checked;updatePreview();}else if(['recipient','sourceSlide','kind'].includes(id)){s[id]=id==='sourceSlide'?Number(e.target.value):e.target.value;updatePreview();}});
  document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target||target.disabled)return;const a=target.dataset.action;s.message='';
    if(a==='reset'){s=fresh();render();return;}
    if(a==='prev'||a==='next'){s.slide=Math.max(5,Math.min(7,s.slide+(a==='next'?1:-1)));if(s.enabled){s.started=Date.now();if(s.slide===6)s.visits++;s.dismissed=false;s.prompt=false;}render();return;}
    if(a==='check'){if(!s.quiz){s.message='Chọn một đáp án trước khi kiểm tra.';}else s.checked=true;render();return;}
    if(a==='form'){s.sourceSlide=s.slide;s.returnMode='form';s.prompt=false;setMode('form');return;}
    if(a==='chat'){s.prompt=false;setMode('chat');return;}
    if(a==='ask-rag'){answerQuery('Truy xuất khác sinh câu trả lời thế nào?');return;}
    if(a==='ask-topk'){answerQuery('Cách chọn top-k?');return;}
    if(a==='ask'){const q=field('query').trim();if(!q){s.message='Hãy viết một câu hỏi hoặc chọn câu hỏi mẫu.';render();return;}answerQuery(q);return;}
    if(a==='explain'){s.sourceSlide=s.slide;s.prompt=false;answerQuery('Truy xuất khác sinh câu trả lời thế nào?');return;}
    if(a==='draft'){s.sourceSlide=s.slide;s.returnMode='answer';s.draft=`Mình đang đọc slide ${s.slide}. Câu hỏi: ${s.query||'Truy xuất khác sinh câu trả lời thế nào?'}\nMình đã đọc lời giải của trợ lý nhưng vẫn cần làm rõ.`;s.share=false;setMode('preview');return;}
    if(a==='preview'){saveForm();if(!s.question.trim()){s.message='Hãy mô tả chỗ bạn muốn hỏi trước khi xem trước.';render();return;}s.returnMode='form';s.draft=s.question;s.share=false;setMode('preview');return;}
    if(a==='send'){savePreview();if(!s.draft.trim()||(s.named&&!s.name.trim())){s.message=!s.draft.trim()?'Nội dung yêu cầu không được để trống.':'Hãy nhập tên giả lập hoặc bỏ chọn kèm tên.';render();return;}s.submitted=true;s.coach=false;s.stage=2;s.prompt=false;render();return;}
    if(a==='edit'||a==='edit-sent'){if(a==='edit')savePreview();s.question=s.draft;s.submitted=false;s.coach=false;s.returnMode='form';setMode('form');return;}
    if(a==='cancel'){savePreview();setMode(s.returnMode);s.message='Chưa gửi yêu cầu. Bạn có thể sửa hoặc tiếp tục học.';render();return;}
    if(a==='withdraw'){s.submitted=false;s.coach=false;s.share=false;render();return;}
    if(a==='coach'){s.coach=true;render();return;}
    if(a==='followup'){s.question='';s.draft='';s.submitted=false;s.coach=false;setMode('form');return;}
    if(a==='close'||a==='understood'){s.stage=a==='understood'?2:0;s.mode=a==='understood'?'learning':'start';s.prompt=false;s.dismissed=true;s.message=a==='understood'?'Bạn có thể thử câu quiz ở bên trái.':'Đã quay lại bài học. Nội dung bạn soạn vẫn được giữ trong phiên.';render();return;}
    if(a==='disable'){disable();return;}
    if(a==='why'){s.why=!s.why;render();return;}
    if(a==='later'||a==='reject'){s.prompt=false;s.dismissed=true;s.message=a==='reject'?'Đã bỏ gợi ý. Không tạo cờ khó khăn hoặc gửi coach.':'Đã để sau. Bạn có thể tiếp tục bài học.';render();}
  });
  setInterval(()=>{if(option!=='c'||!s.enabled||s.slide!==6||s.stage!==0||s.prompt||s.dismissed||s.suggestions>=2)return;const elapsed=Math.floor((Date.now()-s.started)/1000);if(elapsed>=20||s.visits>=2){s.reason=s.visits>=2?`Bạn đã mở slide 6 ${s.visits} lượt trong phiên đã bật gợi ý.`:`Bạn đang ở slide 6 khoảng ${elapsed} giây trong phiên đã bật gợi ý.`;s.suggestions++;s.prompt=true;s.why=false;render();}},500);
  render();
})();
