(() => {
 'use strict';
 const app=document.getElementById('app'),{slides,task,explanation,coachReply}=window.VL_FIXTURE;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const btn=(text,action,kind='',attrs='')=>`<button class="btn ${kind}" data-action="${action}" ${attrs}>${text}</button>`;
 const box=(text,kind='neutral')=>`<div class="box ${kind}">${text}</div>`;
 const blank=()=>({slide:6,stage:0,tab:'tutor',enabled:false,signals:{},suppressed:{},lastPrompt:0,promptCount:0,prompt:null,why:false,chat:[],query:'',draft:'',source:6,recipient:'Lab coach — hỗ trợ khái niệm',named:false,name:'',share:false,mode:'learn',quiz:'',checked:false,notes:'',notice:'',busy:false,submitted:false,coach:false,attachment:null,panel:false,requestId:0});
 let s=blank(),pending=null,lastTick=Date.now(),lastInput=Date.now();
 function signal(n){return s.signals[n]||(s.signals[n]={active:0,visits:0});}
 function labelSignal(p){return p?.kind==='return'?`Slide ${p.slide}: ${p.visits} lượt mở và khoảng ${p.seconds} giây học trong phiên đã bật gợi ý.`:`Slide ${p?.slide}: khoảng ${p?.seconds} giây học trong phiên đã bật gợi ý.`;}
 const duration=n=>Math.floor(n/1000);
 function consent(){return `<div class="radar-consent"><div class="toggle"><label for="enabled">Gợi ý khi học</label><input id="enabled" type="checkbox" role="switch" aria-label="Gợi ý khi học" ${s.enabled?'checked':''}></div><p class="quiet">Chỉ khi bật: dùng thời gian đọc và lượt mở slide trong phiên. Không đọc ghi chú, quiz hay chat để suy đoán. Tắt để xóa tín hiệu.</p></div>`;}
 function lesson(){const x=slides[s.slide];return `<section class="card"><div class="card-title"><h2>Nội dung học</h2><span class="tag">Slide ${s.slide} / 7</span></div><div class="card-body"><article class="slide"><div class="eyebrow">Bài 02 · Hệ thống hỏi đáp</div><h2 style="margin-top:10px">${x.title}</h2><p>${x.text}</p><ul>${x.bullets.map(v=>`<li>${v}</li>`).join('')}</ul>${s.slide===6?'<div class="flow"><span>01 · Câu hỏi</span><span>02 · Tìm tài liệu</span><span>03 · Trả lời</span></div>':''}</article><nav class="nav" aria-label="Chuyển slide">${btn('← Slide trước','prev','',s.slide===5?'disabled':'')}<div class="dots" aria-hidden="true">${[5,6,7].map(n=>`<span class="${s.slide===n?'on':''}"></span>`).join('')}</div>${btn('Slide tiếp →','next','',s.slide===7?'disabled':'')}</nav><section class="quiz"><div class="eyebrow">Tự kiểm tra</div><h3 style="margin-top:6px">Một câu hỏi để tiếp tục</h3><fieldset><legend>Trong RAG, bước nào tìm tài liệu liên quan?</legend>${['Truy xuất','Sinh câu trả lời','Gửi thông báo','Chấm điểm'].map((v,i)=>`<label class="choice"><input type="radio" name="quiz" value="${i}" ${s.quiz===String(i)?'checked':''}>${v}</label>`).join('')}</fieldset>${btn('Kiểm tra câu trả lời','check','subtle')}${s.checked?box(s.quiz==='0'?'Đúng với slide 7: bước 2 là truy xuất. Bạn có thể tiếp tục học.':'Đáp án chưa khớp slide 7. Bạn có thể đọc lại hoặc hỏi thêm; không bị chặn đi tiếp.',s.quiz==='0'?'success':'warn'):''}</section></div></section>`;}
 function prompt(){const p=s.prompt;if(!p)return '';return `<div class="radar-prompt" role="region" aria-label="Gợi ý hỗ trợ"><strong>Muốn làm rõ slide ${p.slide} không?</strong><p class="small" style="margin:8px 0">${slides[p.slide].title}. Mình có thể đang đoán sai; bạn có thể chỉ đang đọc kỹ.</p><button class="linkbutton" data-action="why">${s.why?'Ẩn căn cứ':'Vì sao có gợi ý?'}</button>${s.why?box(esc(labelSignal(p))+' Đây không phải kết luận về năng lực.'):''}<div class="actions">${btn('Gợi ý cách hiểu','hint','primary')}${btn('Nhờ coach','coach-draft')}${btn('Để sau','later')}${btn('Mình không vướng','reject')}</div></div>`;}
 function chat(){return `<div class="conversation" aria-label="Hội thoại Tutor">${s.chat.length?s.chat.map(m=>`<article class="message ${m.role}"><div class="message-meta">${m.role==='user'?'Bạn':'VLearn Tutor · phản hồi mẫu'} <span>Slide ${m.slide}</span></div><p>${esc(m.text)}</p>${m.sources?.length?`<div class="sources">${m.sources.map(n=>btn(`Nguồn · Slide ${n}`,'source','',`data-slide="${n}"`)).join('')}</div><p class="quiet">Nguồn giúp đối chiếu; không bảo đảm lời giải luôn đúng.</p>`:''}</article>`).join(''):box('Bạn có thể hỏi về slide đang đọc hoặc tiếp tục bài học. Tutor dùng tài liệu mẫu của bài 02.')} ${s.busy?'<div class="message ai" role="status">Đang chuẩn bị phản hồi mẫu… '+btn('Dừng','stop')+'</div>':''}</div><form id="chatForm"><label for="query">Câu hỏi về tài liệu</label><textarea id="query" placeholder="Ví dụ: vì sao mô hình vẫn có thể trả lời sai?" ${s.busy?'disabled':''}>${esc(s.query)}</textarea><div class="actions">${btn('Gửi câu hỏi','ask','primary',s.busy?'disabled':'')}${btn('Ví dụ về RAG','example','',s.busy?'disabled':'')}${btn('Truy xuất khác sinh thế nào?','rag','',s.busy?'disabled':'')}</div></form>${s.chat.some(m=>m.role==='ai')?`<div class="actions">${btn('Đã rõ, tiếp tục học','understood','subtle')}${btn('Vẫn chưa rõ → coach','coach-draft')}</div>`:''}<p class="quiet">Phản hồi được soạn sẵn, không gọi AI thật. Câu hỏi ngoài tài liệu sẽ được yêu cầu làm rõ hoặc chuyển coach.</p>`;}
 function draft(){return `<h2>Câu hỏi cho coach</h2><p class="muted small">Bản nháp chưa gửi. Hãy sửa để đúng chỗ bạn đang vướng.</p><label for="sourceSlide">Vị trí cần hỗ trợ</label><select id="sourceSlide">${[5,6,7].map(n=>`<option value="${n}" ${n===s.source?'selected':''}>Slide ${n} — ${slides[n].title}</option>`).join('')}</select><label for="draft">Nội dung yêu cầu</label><textarea id="draft">${esc(s.draft)}</textarea><label for="recipient">Người nhận</label><select id="recipient"><option ${s.recipient.startsWith('Lab')?'selected':''}>Lab coach — hỗ trợ khái niệm</option><option ${s.recipient.startsWith('TA')?'selected':''}>TA — hỗ trợ bài tập</option></select><label class="control"><input id="named" type="checkbox" ${s.named?'checked':''}>Kèm tên của tôi</label>${s.named?`<label for="name">Tên giả lập</label><input id="name" type="text" value="${esc(s.name)}">`:''}${s.enabled&&s.attachment?`<label class="control"><input id="share" type="checkbox" ${s.share?'checked':''}>Kèm tín hiệu đã tạo gợi ý</label><p class="quiet">${esc(labelSignal(s.attachment))}</p>`:''}<p class="quiet">Không tự đính kèm chat, ghi chú hoặc đáp án quiz.</p><div class="actions">${btn('Xem trước','preview','primary')}${btn('Không gửi, quay lại học','cancel')}</div>`;}
 function preview(){return `<h2>Kiểm tra trước khi gửi</h2><div class="preview"><dl><dt>Người nhận</dt><dd>${esc(s.recipient)}</dd><dt>Danh tính</dt><dd>${s.named?esc(s.name):'Không kèm tên'}</dd><dt>Vị trí</dt><dd>Slide ${s.source} — ${slides[s.source].title}</dd><dt>Nội dung</dt><dd>${esc(s.draft)}</dd><dt>Tín hiệu</dt><dd id="previewSignal">${s.share&&s.enabled&&s.attachment?esc(labelSignal(s.attachment)):'Không chia sẻ'}</dd></dl></div>${box('Chỉ mô phỏng gửi; không liên hệ coach thật. Không hứa thời gian phản hồi.')}<div class="actions">${btn('Xác nhận gửi','send','primary')}${btn('Sửa bản nháp','edit')}${btn('Không gửi','cancel')}</div>`;}
 function result(){if(!s.submitted)return `<h2>Tiếp tục theo cách của bạn</h2>${box(s.notice||'Bạn chọn quay lại học. Không gửi yêu cầu cho coach.','success')}<div class="actions">${btn('Quay lại bài học','back','primary')}${btn('Hỏi tiếp','tutor')}${btn('Viết câu hỏi cho coach','manual-draft')}</div>`;return `<h2>Yêu cầu đã gửi · mô phỏng</h2><p class="small muted">${esc(s.recipient)} · Slide ${s.source}</p>${box(esc(s.draft))}${s.coach?box('<strong>Coach · phản hồi mẫu</strong><p style="margin-top:8px">'+esc(coachReply)+'</p>'):box('Yêu cầu đang chờ trong mô phỏng. Bạn có thể tiếp tục học hoặc mở phản hồi mẫu.')}<div class="actions">${!s.coach?btn('Đọc phản hồi mẫu','response','primary')+btn('Sửa yêu cầu','edit')+btn('Thu hồi','withdraw'):btn('Hỏi thêm','manual-draft')}${btn('Tiếp tục bài học','back')}</div><p class="quiet">${s.coach?'Phản hồi đã được mở; không hứa xóa nội dung người nhận đã đọc.':'Có thể thu hồi trước khi mở phản hồi mẫu.'}</p>`;}
 function panel(){const content=s.mode==='draft'?draft():s.mode==='preview'?preview():s.mode==='result'?result():s.tab==='notes'?`<h2>Ghi chú của bạn</h2><label for="notes">Chỉ giữ trong phiên thử</label><textarea id="notes" placeholder="Ghi lại điều bạn muốn nhớ…">${esc(s.notes)}</textarea><p class="quiet">Ghi chú không được dùng để suy đoán hoặc gửi coach.</p>`:(s.submitted?box('Bạn có một yêu cầu coach trong phiên. '+btn('Xem yêu cầu','request')):'')+prompt()+chat();return `<section class="card support-panel"><div class="card-title"><h2>✦ Trợ giảng AI</h2><div class="actions" style="margin:0">${s.enabled?btn('Tắt gợi ý','disable'):''}${btn(s.panel?'Thu gọn':'Mở hỗ trợ','panel')}</div></div>${s.panel?`<div class="tabs" role="group" aria-label="Khu vực hỗ trợ">${btn('Tutor','tutor',s.tab==='tutor'?'subtle':'')}${btn('Ghi chú','notes',s.tab==='notes'?'subtle':'')}${btn('Hỏi coach','manual-draft',s.mode==='draft'?'subtle':'')}</div><div class="card-body">${content}<div class="notice" role="status" aria-live="polite">${s.mode==='result'?'':esc(s.notice)}</div></div>`:`<div class="card-body"><p class="quiet">${s.prompt?'Có một gợi ý đang chờ. Bạn quyết định khi nào mở.':'Bạn có thể tiếp tục đọc tài liệu.'}</p></div>`}</section>`;}
 function render(){app.innerHTML=window.VL_UI.frame({option:'c',stage:s.stage,slide:s.slide,lesson:lesson(),support:panel(),extra:consent(),dock:s.panel,floating:!s.panel?prompt():'',notice:esc(s.notice),hasSuggestion:!!s.prompt});}
 function cancelPending(){s.requestId++;if(pending)clearTimeout(pending);pending=null;s.busy=false;}
 function off(){s.enabled=false;s.signals={};s.suppressed={};s.prompt=null;s.attachment=null;s.share=false;s.notice='Đã tắt và xóa tín hiệu. Hội thoại và ghi chú vẫn giữ trong phiên.';}
 function go(n){if(!slides[n])return;s.slide=n;if(s.enabled)signal(n).visits++;lastTick=Date.now();render();}
 function openDraft(manual=false){cancelPending();s.source=manual?s.slide:(s.prompt?.slide||s.chat.filter(m=>m.role==='user').at(-1)?.slide||s.slide);s.attachment=s.prompt?{...s.prompt}:s.attachment;s.prompt=null;s.stage=1;s.mode='draft';s.tab='tutor';s.panel=true;s.share=false;if(!s.draft){const q=s.chat.filter(m=>m.role==='user').at(-1)?.text;s.draft=q?`Mình muốn hỏi về slide ${s.source}: ${q}\nMình đã xem gợi ý nhưng vẫn cần làm rõ.`:`Mình đang đọc slide ${s.source}: ${slides[s.source].title}. Chỗ mình muốn hỏi: `;}render();}
 function canned(q,n){const t=q.toLowerCase();if(/top.?k|chọn k|đăng nhập|học phí|python|code|điểm thi/.test(t))return {text:'Tài liệu mẫu 5–7 chưa đủ căn cứ trả lời câu này. Bạn có thể nói rõ phần liên quan đến RAG hoặc nhờ coach. Mình không tự đoán.',sources:[]};if(/ví dụ|minh họa/.test(t))return {text:'Ví dụ bạn hỏi chính sách đổi trả: bước truy xuất tìm đoạn chính sách liên quan; bước sinh dùng đoạn đó để viết câu trả lời. Nếu đoạn tìm được không chứa điều bạn hỏi, lời giải vẫn có thể sai. Theo bạn, đâu là bước tìm tài liệu?',sources:[6,7]};if(/sai|ảo giác|căn cứ|hallucin|tin|đúng/.test(t))return {text:'Theo slide 5, câu trả lời trôi chảy chưa chắc đúng. RAG bổ sung tài liệu để đối chiếu, nhưng không bảo đảm mô hình luôn đúng. Bạn hãy kiểm tra đoạn nguồn có thực sự hỗ trợ kết luận không.',sources:[5,6]};if(/bước|quy trình|thứ tự/.test(t))return {text:'Bốn bước: nhận câu hỏi → tìm đoạn tài liệu → đưa câu hỏi và đoạn đó vào mô hình → sinh câu trả lời. Bước 2 là truy xuất, bước 4 là sinh. Bạn thử xác định bước đang vướng nhé.',sources:[7]};if(/rag|truy xuất|sinh|retrieval|tài liệu/.test(t))return {text:explanation+' Theo bạn, bước nào tìm tài liệu trước khi trả lời?',sources:[6,7]};if(/chưa rõ|chưa hiểu|giải thích|giúp/.test(t))return {text:`Bạn muốn làm rõ ${n===5?'cách kiểm tra căn cứ':n===7?'thứ tự các bước':'truy xuất hay sinh câu trả lời'}? Nói rõ một chỗ để mình gợi ý tiếp.`,sources:[n]};return {text:'Mình chưa xác định được chỗ bạn muốn hỏi. Bạn có thể nêu một thuật ngữ hoặc bước trong slide 5–7; nếu câu hỏi nằm ngoài tài liệu, hãy chuyển coach.',sources:[]};}
 function ask(q,n=s.slide){if(s.busy)return;q=q.trim();if(!q){s.notice='Hãy viết câu hỏi trước khi gửi.';render();return;}s.query='';s.stage=1;s.mode='learn';s.tab='tutor';s.panel=true;s.prompt=null;s.chat.push({role:'user',text:q,slide:n});s.busy=true;s.notice='';const id=++s.requestId;render();pending=setTimeout(()=>{if(id!==s.requestId)return;s.chat.push({role:'ai',slide:n,...canned(q,n)});s.busy=false;pending=null;render();},600);}
 document.addEventListener('submit',e=>{if(e.target.id==='chatForm'){e.preventDefault();ask(s.query);}});
 document.addEventListener('input',e=>{lastInput=Date.now();if(['query','draft','name','notes'].includes(e.target.id))s[e.target.id]=e.target.value;});
 document.addEventListener('pointerdown',()=>lastInput=Date.now());document.addEventListener('keydown',()=>lastInput=Date.now());
 document.addEventListener('visibilitychange',()=>{lastTick=Date.now();if(!document.hidden)lastInput=Date.now();});
 document.addEventListener('change',e=>{const id=e.target.id;if(e.target.name==='quiz'){s.quiz=e.target.value;s.checked=false;return;}if(id==='enabled'){if(e.target.checked){s.enabled=true;s.signals={};s.suppressed={};signal(s.slide).visits=1;s.notice='Gợi ý chỉ dùng tín hiệu kể từ lúc bạn bật.';lastTick=lastInput=Date.now();}else off();render();}else if(id==='sourceSlide')s.source=Number(e.target.value);else if(id==='recipient')s.recipient=e.target.value;else if(id==='named'){s.named=e.target.checked;render();}else if(id==='share')s.share=e.target.checked;});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action;s.notice='';
 if(a==='reset'){window.VL_UI.reset();cancelPending();s=blank();lastTick=lastInput=Date.now();render();return;}
 if(a==='goto'){go(Number(el.dataset.slide));return;}
 if(a==='tutor-open'){s.panel=true;s.stage=0;s.tab='tutor';s.mode='learn';render();return;}
 if(a==='notes-open'){s.panel=true;s.tab='notes';s.mode='learn';render();return;}
 if(a==='prev'||a==='next'){go(s.slide+(a==='next'?1:-1));return;}
 if(a==='source'){go(Number(el.dataset.slide));return;}
 if(a==='check'){if(!s.quiz)s.notice='Chọn một đáp án trước khi kiểm tra.';else s.checked=true;render();return;}
 if(a==='disable'){off();render();return;}
 if(a==='panel'){s.panel=!s.panel;render();return;}
 if(a==='why'){s.why=!s.why;render();return;}
 if(a==='later'||a==='reject'){if(s.prompt){s.suppressed[s.prompt.slide]=a==='reject'?Infinity:Date.now()+60000;s.prompt=null;}s.notice=a==='reject'?'Đã bỏ gợi ý cho slide này. Không gắn cờ hoặc gửi coach.':'Đã để sau. Bạn có thể tự hỏi bất cứ lúc nào.';render();return;}
 if(a==='hint'){const p=s.prompt;if(!p)return;s.attachment={...p};ask(p.slide===5?'Vì sao câu trả lời có thể sai?':p.slide===7?'Giải thích các bước RAG':'Truy xuất khác sinh câu trả lời thế nào?',p.slide);return;}
 if(a==='ask'){ask(s.query);return;}
 if(a==='rag'||a==='example'){ask(a==='rag'?'Truy xuất khác sinh câu trả lời thế nào?':'Cho mình một ví dụ về RAG');return;}
 if(a==='stop'){cancelPending();s.notice='Đã dừng. Câu hỏi vẫn ở hội thoại; bạn có thể viết lại hoặc nhờ coach.';render();return;}
 if(a==='coach-draft'||a==='manual-draft'){openDraft(a==='manual-draft');return;}
 if(a==='notes'||a==='tutor'){s.tab=a;s.mode='learn';s.panel=true;s.stage=0;s.prompt=null;render();return;}
 if(a==='preview'){if(!s.draft.trim()||(s.named&&!s.name.trim())){s.notice=!s.draft.trim()?'Nội dung không được để trống.':'Nhập tên giả lập hoặc bỏ kèm tên.';render();return;}s.mode='preview';render();return;}
 if(a==='edit'){s.mode='draft';s.stage=1;s.submitted=false;s.coach=false;render();return;}
 if(a==='send'){s.submitted=true;s.coach=false;s.mode='result';s.stage=2;render();return;}
 if(a==='withdraw'){s.submitted=false;s.mode='result';s.stage=2;s.share=false;s.notice='Đã thu hồi trước khi mở phản hồi mẫu.';render();return;}
 if(a==='request'){s.mode='result';s.stage=2;render();return;}
 if(a==='response'){s.coach=true;render();return;}
 if(a==='understood'){cancelPending();s.stage=2;s.mode='result';s.submitted=false;s.notice='Bạn chọn tiếp tục học và tự kiểm tra bằng quiz. Không gửi dữ liệu cho coach.';render();return;}
 if(a==='cancel'||a==='back'){s.stage=0;s.mode='learn';s.tab='tutor';s.prompt=null;lastTick=Date.now();s.notice='Đã quay lại bài học. Bản nháp và hội thoại vẫn giữ trong phiên.';render();return;}
 });
 setInterval(()=>{const now=Date.now(),delta=Math.min(1000,Math.max(0,now-lastTick));lastTick=now;if(!s.enabled||document.hidden||now-lastInput>90000||s.stage!==0||s.tab!=='tutor'||s.mode!=='learn'||s.busy)return;const x=signal(s.slide);x.active+=delta;const focused=document.activeElement;if(s.query.trim()||focused?.matches('textarea,input[type=text]'))return;if(s.prompt||s.promptCount>=2||now<(s.suppressed[s.slide]||0)||s.lastPrompt&&now-s.lastPrompt<60000)return;const kind=x.visits>=2&&x.active>=15000?'return':x.active>=45000?'time':null;if(!kind)return;s.prompt={slide:s.slide,kind,visits:x.visits,seconds:duration(x.active)};s.why=false;s.promptCount++;s.lastPrompt=now;s.notice=`Có gợi ý cho slide ${s.slide}. Bạn có thể mở Trợ giảng hoặc xem dưới tài liệu.`;render();},500);
 render();
})();
